[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[variables]
PIP_BREAK_SYSTEM_PACKAGES = "1"

[phases.install]
cmds = [
    "pip install 'uvicorn[standard]' fastapi structlog pydantic github-copilot-sdk",
    "pip install -e ."
]

[start]
cmd = "python server.py"
